export const FETCH_POIS = "FETCH_POIS";
export const PERMISSIONS_ANSWER_ISALLOW = "PERMISSIONS_ANSWER_ISALLOW";
export const PERMISSIONS_ANSWER_ISDENY = "PERMISSIONS_ANSWER_ISDENY";
export const CURRENT_LOCATION = "CURRENT_LOCATION";
